export const GEOLOCATION_COOKIE_NAME: string = 'geolocation'
export const CITY_COOKIE_NAME: string = 'city'
export const THEME_COOKIE_NAME: string = 'theme'
export const UNIT_SYSTEM_COOKIE_NAME: string = 'unitSystem'
export const LANGUAGE_COOKIE_NAME: string = 'language'
export const HOUR_CYCLE_COOKIE_NAME: string = 'hourCycle'
