export enum WeatherDescription {
  CLEAR_SKY = 'clear sky',
  FEW_CLOUDS = 'few clouds',
  SCATTERED_CLOUDS = 'scattered clouds',
  BROKEN_CLOUDS = 'broken clouds',
  OVERCAST_CLOUDS = 'overcast clouds',
  RAIN = 'rain',
  LIGHT_RAIN = 'light rain',
  HEAVY_RAIN = 'heavy intensity rain',
  LIGHT_SHOWER_RAIN = 'light intensity shower rain',
  HEAVY_SHOWER_RAIN = 'heavy intensity shower rain',
  SHOWER_RAIN = 'shower rain',
  MODERATE_RAIN = 'moderate rain',
  THUNDERSTORM = 'thunderstorm',
  SNOW = 'snow',
  LIGHT_SHOW = 'light snow',
  HAZE = 'haze',
  MIST = 'mist',
  FOG = 'fog'
}
